# -*- coding: utf-8 -*-
"""Batimetría - Agu

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1djSXXSpVwjKlbDpk1v9ds-kep2Vi34BN
"""

# Instalar librerías geoespaciales (Colab no las trae por defecto)
!pip install -q geopandas rasterio shapely

# ====================================================================
# PIPELINE COMPLETO - Raster de profundidad Río Hondo 2001, derivado -
# de datos batimetricos
# ====================================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from shapely.geometry import Polygon
from scipy.interpolate import griddata
from scipy.spatial import cKDTree
import rasterio
from rasterio.transform import from_origin
from rasterio.features import geometry_mask
from google.colab import drive
drive.mount('/content/drive')

# ---- 1. Cargar datos ----
pts = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/rio_hondo_2001_puntos.csv')
perim = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/rio_hondo_2001_perimetro.csv')

# Corregir columnas invertidas (el archivo original trae "x"=Norte, "y"=Este)
pts = pts.rename(columns={'x': 'este', 'y': 'norte'})
perim = perim.rename(columns={'x': 'este', 'y': 'norte'})

este = pts.este.values
norte = pts.norte.values
prof = pts.profundidad_m.values

# ---- 2. CRS ----
CRS = "EPSG:22183"

# ---- 3. Polígono del perímetro navegado ----
poly_coords = list(zip(perim.este, perim.norte))
if poly_coords[0] != poly_coords[-1]:
    poly_coords.append(poly_coords[0])
poly = Polygon(poly_coords)
print("¿Polígono válido?", poly.is_valid, "- área aprox (km²):", poly.area / 1e6)

# ---- 4. Grilla de salida ----
res = 30  # metros/pixel
xmin, ymin, xmax, ymax = poly.bounds
gx, gy = np.meshgrid(
    np.arange(xmin, xmax, res),
    np.arange(ymax, ymin, -res)
)
print(f"Grilla: {gx.shape[0]} filas x {gx.shape[1]} columnas")

# ---- 5. Interpolación ----
z_lin = griddata((este, norte), prof, (gx, gy), method='linear')
z_near = griddata((este, norte), prof, (gx, gy), method='nearest')
z = np.where(np.isnan(z_lin), z_near, z_lin)

# ---- 6. Recorte al perímetro navegado ----
transform = from_origin(xmin, ymax, res, res)
mask = geometry_mask([poly], transform=transform, invert=True, out_shape=z.shape)
z_masked = np.where(mask, z, np.nan)

# ---- 7. Visualizar antes de exportar ----
fig, ax = plt.subplots(figsize=(10, 8))
im = ax.imshow(z_masked, cmap='viridis', extent=[xmin, xmax, ymin, ymax])
plt.colorbar(im, label='Profundidad (m)')
ax.set_title('Raster de profundidad interpolado - Río Hondo 2001')
plt.show()

# ---- 8. Exportar a GeoTIFF ----
out_path = '/content/drive/MyDrive/Colab Notebooks/rio_hondo_profundidad_2001.tif'
with rasterio.open(
    out_path, 'w', driver='GTiff',
    height=z_masked.shape[0], width=z_masked.shape[1],
    count=1, dtype='float32', crs=CRS, transform=transform,
    nodata=np.nan
) as dst:
    dst.write(z_masked.astype('float32'), 1)

print("Guardado en:", out_path)

# ---- 9.(Opcional) Capa de confianza espacial ----
tree = cKDTree(np.column_stack([este, norte]))
grid_points = np.column_stack([gx.ravel(), gy.ravel()])
dist, _ = tree.query(grid_points)
dist_masked = np.where(mask, dist.reshape(gx.shape), np.nan)

out_path_conf = '/content/drive/MyDrive/Colab Notebooks/rio_hondo_confianza_2001.tif'
with rasterio.open(
    out_path_conf, 'w', driver='GTiff',
    height=dist_masked.shape[0], width=dist_masked.shape[1],
    count=1, dtype='float32', crs=CRS, transform=transform,
    nodata=np.nan
) as dst:
    dst.write(dist_masked.astype('float32'), 1)

print("Capa de confianza guardada en:", out_path_conf)

import pandas as pd
import matplotlib.pyplot as plt

# 1. Cargar los puntos
pts = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/rio_hondo_2001_puntos.csv')
pts.head()

# 2. Cargar el perímetro navegado (ajustá el nombre si lo subiste con otro)
perim = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/rio_hondo_2001_perimetro.csv')

# 3. Visualizar puntos + perímetro
# OJO: la columna "y" del CSV es en realidad la coordenada Este,
# y la columna "x" es la coordenada Norte (headers originales invertidos)
fig, ax = plt.subplots(figsize=(10, 8))
sc = ax.scatter(pts.y, pts.x, c=pts.profundidad_m, cmap='viridis_r', s=2)
ax.plot(perim.y, perim.x, color='red', linewidth=0.8, label='Perímetro navegado')
plt.colorbar(sc, label='Profundidad (m)')
ax.set_xlabel('Este (m)')
ax.set_ylabel('Norte (m)')
ax.set_aspect('equal')
ax.legend()
plt.title('Río Hondo 2001 - puntos batimétricos + perímetro')
plt.show()

